In [3]:
import numpy as np
# 1D array
arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [13]:
arr2 = np.array([1,2,3,4,5])
a = arr2.reshape(1,5)
print(a)
a.shape

[[1 2 3 4 5]]


(1, 5)

In [10]:
arr2 = np.array([[1,2,3,4,5]])
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]]
(1, 5)


In [11]:
# 2D array
arr2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr2)
print(arr2.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
(2, 5)


In [16]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [20]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [23]:
#Identity matrix

np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [27]:
## Attributes of Numpy Array
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Array:\n", arr)
print("Shape:", arr.shape)  # Output: (2, 3)
print("Number of dimensions:", arr.ndim)  # Output: 2
print("Size (number of elements):", arr.size)  # Output: 6
print("Data type:", arr.dtype)  # Output: int32 (may vary based on platform)
print("Item size (in bytes):", arr.itemsize)  # Output: 8 (may vary based on platform)

Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimensions: 2
Size (number of elements): 6
Data type: int32
Item size (in bytes): 4


In [42]:
# Numpy vectorized operation
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

#Element wise addition
print("Addition: ", arr1+arr2)
#k = zip(arr1,arr2) # Just checking zip method
#print(list(k))

#Element wise substraction

print("Substraction: ", arr2-arr1)

#Element wise Multiplication, same with division as well

print("Multiplication: ", arr2*arr1) 

Addition:  [11 22 33 44 55]
Substraction:  [ 9 18 27 36 45]
Multiplication:  [ 10  40  90 160 250]


In [47]:
##Universal function

arr = np.array([1,2,3,4,5,6])

#Square root
print(np.sqrt(arr))

#Exponential
print(np.exp(arr))

#Sin
print(np.sin(arr))

# Natural log

print(np.log(arr))

[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591
 403.42879349]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [68]:
#Slicing and indexing

arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array: \n", arr)

arr[2,2]

arr[1:,2:]
arr[0:2,2:]
arr[1:3,1:3]

Array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


array([[ 6,  7],
       [10, 11]])

In [73]:
arr[0,0] = 100
arr[1:] = 50
arr

array([[100,   2,   3,   4],
       [ 50,  50,  50,  50],
       [ 50,  50,  50,  50]])

In [75]:
#Statistical concept--Normalization
#to have a mean of 0 and standard deviation of 1

# Calculate the mean and standard deviation
data = np.array([1, 2, 3, 4, 5])
mean = np.mean(data)
std_dev = np.std(data)

# Normalize the data
normalized_data = (data - mean) / std_dev
print("Normalized data:", normalized_data)

Normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [81]:
data = np.array([1,2,3,4,5,6,7,8,9,10])

#Mean
mean = np.mean(data)
print(mean)

#Median
Median = np.median(data)
print(Median)

#Std
std = np.std(data)
print(std)

#Variance
variance = np.var(data)
print(variance)

5.5
5.5
2.8722813232690143
8.25


In [92]:
#Logical Operation

data = np.arange(0,11)
data>5
data[(data>=5) & (data<=8)]

array([5, 6, 7, 8])